apiVersion: v1
kind: ConfigMap
metadata:
  name: otelcol-config
  namespace: observability
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: :4317
            max_recv_msg_size_mib: 100000
          http:            # :4318
    processors:
      batch: {}
      memory_limiter:
        check_interval: 2s
        limit_percentage: 75
        spike_limit_percentage: 15
    exporters:
      debug: {}
    extensions:
      health_check:
        endpoint: 0.0.0.0:13133
        path: /
      pprof: {}            # :1777
      zpages: {}           # :55679
    service:
      extensions: [health_check, pprof, zpages]
      pipelines:
        traces:
          receivers:  [otlp]
          processors: [memory_limiter, batch]
          exporters:  [debug]
        metrics:
          receivers:  [otlp]
          processors: [memory_limiter, batch]
          exporters:  [debug]
        logs:
          receivers:  [otlp]
          processors: [memory_limiter, batch]
          exporters:  [debug]