// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: listener/v1/listener.proto

package listenerv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/kaasops/envoy-xds-controller/pkg/api/grpc/listener/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// VirtualServiceStoreServiceName is the fully-qualified name of the VirtualServiceStoreService
	// service.
	VirtualServiceStoreServiceName = "listener.v1.VirtualServiceStoreService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// VirtualServiceStoreServiceListVirtualServiceProcedure is the fully-qualified name of the
	// VirtualServiceStoreService's ListVirtualService RPC.
	VirtualServiceStoreServiceListVirtualServiceProcedure = "/listener.v1.VirtualServiceStoreService/ListVirtualService"
)

// VirtualServiceStoreServiceClient is a client for the listener.v1.VirtualServiceStoreService
// service.
type VirtualServiceStoreServiceClient interface {
	ListVirtualService(context.Context, *connect.Request[v1.ListVirtualServiceRequest]) (*connect.Response[v1.ListVirtualServiceResponse], error)
}

// NewVirtualServiceStoreServiceClient constructs a client for the
// listener.v1.VirtualServiceStoreService service. By default, it uses the Connect protocol with the
// binary Protobuf Codec, asks for gzipped responses, and sends uncompressed requests. To use the
// gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewVirtualServiceStoreServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) VirtualServiceStoreServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	virtualServiceStoreServiceMethods := v1.File_listener_v1_listener_proto.Services().ByName("VirtualServiceStoreService").Methods()
	return &virtualServiceStoreServiceClient{
		listVirtualService: connect.NewClient[v1.ListVirtualServiceRequest, v1.ListVirtualServiceResponse](
			httpClient,
			baseURL+VirtualServiceStoreServiceListVirtualServiceProcedure,
			connect.WithSchema(virtualServiceStoreServiceMethods.ByName("ListVirtualService")),
			connect.WithClientOptions(opts...),
		),
	}
}

// virtualServiceStoreServiceClient implements VirtualServiceStoreServiceClient.
type virtualServiceStoreServiceClient struct {
	listVirtualService *connect.Client[v1.ListVirtualServiceRequest, v1.ListVirtualServiceResponse]
}

// ListVirtualService calls listener.v1.VirtualServiceStoreService.ListVirtualService.
func (c *virtualServiceStoreServiceClient) ListVirtualService(ctx context.Context, req *connect.Request[v1.ListVirtualServiceRequest]) (*connect.Response[v1.ListVirtualServiceResponse], error) {
	return c.listVirtualService.CallUnary(ctx, req)
}

// VirtualServiceStoreServiceHandler is an implementation of the
// listener.v1.VirtualServiceStoreService service.
type VirtualServiceStoreServiceHandler interface {
	ListVirtualService(context.Context, *connect.Request[v1.ListVirtualServiceRequest]) (*connect.Response[v1.ListVirtualServiceResponse], error)
}

// NewVirtualServiceStoreServiceHandler builds an HTTP handler from the service implementation. It
// returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewVirtualServiceStoreServiceHandler(svc VirtualServiceStoreServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	virtualServiceStoreServiceMethods := v1.File_listener_v1_listener_proto.Services().ByName("VirtualServiceStoreService").Methods()
	virtualServiceStoreServiceListVirtualServiceHandler := connect.NewUnaryHandler(
		VirtualServiceStoreServiceListVirtualServiceProcedure,
		svc.ListVirtualService,
		connect.WithSchema(virtualServiceStoreServiceMethods.ByName("ListVirtualService")),
		connect.WithHandlerOptions(opts...),
	)
	return "/listener.v1.VirtualServiceStoreService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case VirtualServiceStoreServiceListVirtualServiceProcedure:
			virtualServiceStoreServiceListVirtualServiceHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedVirtualServiceStoreServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedVirtualServiceStoreServiceHandler struct{}

func (UnimplementedVirtualServiceStoreServiceHandler) ListVirtualService(context.Context, *connect.Request[v1.ListVirtualServiceRequest]) (*connect.Response[v1.ListVirtualServiceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("listener.v1.VirtualServiceStoreService.ListVirtualService is not implemented"))
}
