apiVersion: v1
kind: ConfigMap
metadata:
  name: ldap-configmap
  labels:
    app: ldap
data:
  config-ldap.ldif: |-
    # dn: dc=example,dc=org
    # objectClass: dcObject
    # objectClass: organization
    # o: Example Company
    # dc: example

    dn: ou=People,dc=example,dc=org
    objectClass: organizationalUnit
    ou: People

    dn: cn=jane,ou=People,dc=example,dc=org
    objectClass: person
    objectClass: inetOrgPerson
    sn: doe
    cn: jane
    mail: janedoe@example.com
    userpassword: foo

    dn: cn=john,ou=People,dc=example,dc=org
    objectClass: person
    objectClass: inetOrgPerson
    sn: doe
    cn: john
    mail: johndoe@example.com
    userpassword: bar
    
    dn: cn=tester,ou=People,dc=example,dc=org
    objectClass: person
    objectClass: inetOrgPerson
    sn: tester
    cn: tester
    mail: tester@example.com
    userpassword: tester
    
    dn: cn=user,ou=People,dc=example,dc=org
    objectClass: person
    objectClass: inetOrgPerson
    sn: user
    cn: user
    mail: user@example.com
    userpassword: user

    # Group definitions.

    dn: ou=Groups,dc=example,dc=org
    objectClass: organizationalUnit
    ou: Groups

    dn: cn=admins,ou=Groups,dc=example,dc=org
    objectClass: groupOfNames
    cn: admins
    member: cn=john,ou=People,dc=example,dc=org

    dn: cn=developers,ou=Groups,dc=example,dc=org
    objectClass: groupOfNames
    cn: developers
    member: cn=jane,ou=People,dc=example,dc=org

    dn: cn=testers,ou=Groups,dc=example,dc=org
    objectClass: groupOfNames
    cn: testers
    member: cn=tester,ou=People,dc=example,dc=org
    
    dn: cn=users,ou=Groups,dc=example,dc=org
    objectClass: groupOfNames
    cn: users
    member: cn=user,ou=People,dc=example,dc=org