{{- if .Values.webhook.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: envoy-xds-controller-webhook-service
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  {{- with .Values.extraLabels }}
    {{ toYaml . | indent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: 443
    name: https
    protocol: TCP
    targetPort: {{ .Values.webhook.port }}
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
{{- end -}}

