{{- if .Values.config -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  CONFIG: '{{ .Values.config | toJson }}'
{{- end }}