// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: virtual_service_template/v1/virtual_service_template.proto

package virtual_service_templatev1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/kaasops/envoy-xds-controller/pkg/api/grpc/virtual_service_template/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// VirtualServiceTemplateStoreServiceName is the fully-qualified name of the
	// VirtualServiceTemplateStoreService service.
	VirtualServiceTemplateStoreServiceName = "virtual_service_template.v1.VirtualServiceTemplateStoreService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// VirtualServiceTemplateStoreServiceListVirtualServiceTemplateProcedure is the fully-qualified name
	// of the VirtualServiceTemplateStoreService's ListVirtualServiceTemplate RPC.
	VirtualServiceTemplateStoreServiceListVirtualServiceTemplateProcedure = "/virtual_service_template.v1.VirtualServiceTemplateStoreService/ListVirtualServiceTemplate"
)

// VirtualServiceTemplateStoreServiceClient is a client for the
// virtual_service_template.v1.VirtualServiceTemplateStoreService service.
type VirtualServiceTemplateStoreServiceClient interface {
	ListVirtualServiceTemplate(context.Context, *connect.Request[v1.ListVirtualServiceTemplateRequest]) (*connect.Response[v1.ListVirtualServiceTemplateResponse], error)
}

// NewVirtualServiceTemplateStoreServiceClient constructs a client for the
// virtual_service_template.v1.VirtualServiceTemplateStoreService service. By default, it uses the
// Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewVirtualServiceTemplateStoreServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) VirtualServiceTemplateStoreServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	virtualServiceTemplateStoreServiceMethods := v1.File_virtual_service_template_v1_virtual_service_template_proto.Services().ByName("VirtualServiceTemplateStoreService").Methods()
	return &virtualServiceTemplateStoreServiceClient{
		listVirtualServiceTemplate: connect.NewClient[v1.ListVirtualServiceTemplateRequest, v1.ListVirtualServiceTemplateResponse](
			httpClient,
			baseURL+VirtualServiceTemplateStoreServiceListVirtualServiceTemplateProcedure,
			connect.WithSchema(virtualServiceTemplateStoreServiceMethods.ByName("ListVirtualServiceTemplate")),
			connect.WithClientOptions(opts...),
		),
	}
}

// virtualServiceTemplateStoreServiceClient implements VirtualServiceTemplateStoreServiceClient.
type virtualServiceTemplateStoreServiceClient struct {
	listVirtualServiceTemplate *connect.Client[v1.ListVirtualServiceTemplateRequest, v1.ListVirtualServiceTemplateResponse]
}

// ListVirtualServiceTemplate calls
// virtual_service_template.v1.VirtualServiceTemplateStoreService.ListVirtualServiceTemplate.
func (c *virtualServiceTemplateStoreServiceClient) ListVirtualServiceTemplate(ctx context.Context, req *connect.Request[v1.ListVirtualServiceTemplateRequest]) (*connect.Response[v1.ListVirtualServiceTemplateResponse], error) {
	return c.listVirtualServiceTemplate.CallUnary(ctx, req)
}

// VirtualServiceTemplateStoreServiceHandler is an implementation of the
// virtual_service_template.v1.VirtualServiceTemplateStoreService service.
type VirtualServiceTemplateStoreServiceHandler interface {
	ListVirtualServiceTemplate(context.Context, *connect.Request[v1.ListVirtualServiceTemplateRequest]) (*connect.Response[v1.ListVirtualServiceTemplateResponse], error)
}

// NewVirtualServiceTemplateStoreServiceHandler builds an HTTP handler from the service
// implementation. It returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewVirtualServiceTemplateStoreServiceHandler(svc VirtualServiceTemplateStoreServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	virtualServiceTemplateStoreServiceMethods := v1.File_virtual_service_template_v1_virtual_service_template_proto.Services().ByName("VirtualServiceTemplateStoreService").Methods()
	virtualServiceTemplateStoreServiceListVirtualServiceTemplateHandler := connect.NewUnaryHandler(
		VirtualServiceTemplateStoreServiceListVirtualServiceTemplateProcedure,
		svc.ListVirtualServiceTemplate,
		connect.WithSchema(virtualServiceTemplateStoreServiceMethods.ByName("ListVirtualServiceTemplate")),
		connect.WithHandlerOptions(opts...),
	)
	return "/virtual_service_template.v1.VirtualServiceTemplateStoreService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case VirtualServiceTemplateStoreServiceListVirtualServiceTemplateProcedure:
			virtualServiceTemplateStoreServiceListVirtualServiceTemplateHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedVirtualServiceTemplateStoreServiceHandler returns CodeUnimplemented from all
// methods.
type UnimplementedVirtualServiceTemplateStoreServiceHandler struct{}

func (UnimplementedVirtualServiceTemplateStoreServiceHandler) ListVirtualServiceTemplate(context.Context, *connect.Request[v1.ListVirtualServiceTemplateRequest]) (*connect.Response[v1.ListVirtualServiceTemplateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("virtual_service_template.v1.VirtualServiceTemplateStoreService.ListVirtualServiceTemplate is not implemented"))
}
