{{- if ne .Values.metrics.address "0" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "chart.fullname" . }}-metrics-auth-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "chart.fullname" . }}-metrics-auth-role
subjects:
- kind: ServiceAccount
  name: {{ template "chart.fullname" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}