{{- if ne .Values.metrics.address "0" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "chart.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  {{- with .Values.extraLabels }}
    {{ toYaml . | indent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: https
      port: 8443
      protocol: TCP
      targetPort: 8443
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
{{- end }}