apiVersion: v1
kind: Service
metadata:
  name: {{ template "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  {{- with .Values.extraLabels }}
    {{ toYaml . | indent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.xds.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
