{{- if .Values.auth.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: access-control-model
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  model.conf: |-
    [request_definition]
    r = sub, dom, obj, act

    [policy_definition]
    p = sub, dom, obj, act

    [role_definition]
    g = _, _, _

    [policy_effect]
    e = some(where (p.eft == allow))

    [matchers]
    m = g(r.sub, p.sub, r.dom) && r.dom == p.dom && globMatch(r.obj, p.obj) && r.act == p.act || r.sub == "superuser"
  policy.csv: |-
    p, virtual-service-creator, *, *, list-virtual-services
    p, virtual-service-creator, *, *, get-virtual-service
    p, virtual-service-creator, *, *, create-virtual-service
    p, virtual-service-creator, *, *, update-virtual-service

    p, virtual-service-reader, *, *, list-virtual-services
    p, virtual-service-reader, *, *, get-virtual-service
    p, virtual-service-reader, *, *, list-access-groups
    p, virtual-service-reader, *, *, list-node-ids
    p, virtual-service-reader, *, *, list-access-log-configs
{{- end }}