{{- if .Values.auth.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: access-control-model
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  MODEL: |-
    [request_definition]
    r = sub, dom, obj, act

    [policy_definition]
    p = sub, dom, obj, act

    [role_definition]
    g = _, _, _

    [policy_effect]
    e = some(where (p.eft == allow))

    [matchers]
    m = g(r.sub, p.sub, r.dom) && r.dom == p.dom && globMatch(r.obj, p.obj) && r.act == p.act || r.sub == "superuser"
{{- end }}