name: E2E Tests

on:
  push:
  pull_request:

jobs:
  test-e2e:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '~1.24'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Pre-pull base images
        run: |
          docker pull golang:1.24
          docker pull gcr.io/distroless/static:nonroot
          docker pull alpine:3.22.1

      - name: Install the latest version of kind
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/latest/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind

      - name: Verify kind installation
        run: kind version

      - name: Create kind cluster
        run: kind create cluster

      - name: Running Test e2e
        run: |
          go mod tidy
          make test-e2e
        env:
          DOCKER_BUILDKIT: 1
          BUILDKIT_PROGRESS: plain
